subscription_id  = "ef3ac21e-bc8a-4281-848b-3e98aab8f89e"
location         = "North Europe"
customer         = "intern"
environment      = "dev"
backend_base_url = "https://app-count-intern-dev-backend.azurewebsites.net/api/v1"
backend_api_key  = "xejbndlhntftpljr"
